[build]
  base = "Netflix-Clone-2025"
  publish = "build"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_KEY = "YOUR_API_KEY_HERE"
